/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== Cholesky ==================
static const unsigned char temp_binary_data_0[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_CHOLESKY_MODULE_H\r\n"
"#define EIGEN_CHOLESKY_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"#include \"Jacobi\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup Cholesky_Module Cholesky module\r\n"
"  *\r\n"
"  *\r\n"
"  *\r\n"
"  * This module provides two variants of the Cholesky decomposition for selfadjoint (hermitian) matrices.\r\n"
"  * Those decompositions are also accessible via the following methods:\r\n"
"  *  - MatrixBase::llt()\r\n"
"  *  - MatrixBase::ldlt()\r\n"
"  *  - SelfAdjointView::llt()\r\n"
"  *  - SelfAdjointView::ldlt()\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Cholesky>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/Cholesky/LLT.h\"\r\n"
"#include \"src/Cholesky/LDLT.h\"\r\n"
"#ifdef EIGEN_USE_LAPACKE\r\n"
"#ifdef EIGEN_USE_MKL\r\n"
"#include \"mkl_lapacke.h\"\r\n"
"#else\r\n"
"#include \"src/misc/lapacke.h\"\r\n"
"#endif\r\n"
"#include \"src/Cholesky/LLT_LAPACKE.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_CHOLESKY_MODULE_H\r\n";

const char* Cholesky = (const char*) temp_binary_data_0;

//================== CholmodSupport ==================
static const unsigned char temp_binary_data_1[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_CHOLMODSUPPORT_MODULE_H\r\n"
"#define EIGEN_CHOLMODSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"extern \"C\" {\r\n"
"  #include <cholmod.h>\r\n"
"}\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup CholmodSupport_Module CholmodSupport module\r\n"
"  *\r\n"
"  * This module provides an interface to the Cholmod library which is part of the <a href=\"http://www.suitesparse.com\">suitesparse</a> package.\r\n"
"  * It provides the two following main factorization classes:\r\n"
"  * - class CholmodSupernodalLLT: a supernodal LLT Cholesky factorization.\r\n"
"  * - class CholmodDecomposiiton: a general L(D)LT Cholesky factorization with automatic or explicit runtime selection of the underlying factorization method (supernodal or simplicial).\r\n"
"  *\r\n"
"  * For the sake of completeness, this module also propose the two following classes:\r\n"
"  * - class CholmodSimplicialLLT\r\n"
"  * - class CholmodSimplicialLDLT\r\n"
"  * Note that these classes does not bring any particular advantage compared to the built-in\r\n"
"  * SimplicialLLT and SimplicialLDLT factorization classes.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/CholmodSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the cholmod headers must be accessible from the include paths, and your binary must be linked to the cholmod library and its dependencies.\r\n"
"  * The dependencies depend on how cholmod has been compiled.\r\n"
"  * For a cmake based project, you can use our FindCholmod.cmake module to help you in this task.\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/CholmodSupport/CholmodSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_CHOLMODSUPPORT_MODULE_H\r\n"
"\r\n";

const char* CholmodSupport = (const char*) temp_binary_data_1;

//================== Core ==================
static const unsigned char temp_binary_data_2[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2008 Gael Guennebaud <gael.guennebaud@inria.fr>\r\n"
"// Copyright (C) 2007-2011 Benoit Jacob <jacob.benoit.1@gmail.com>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_CORE_H\r\n"
"#define EIGEN_CORE_H\r\n"
"\r\n"
"// first thing Eigen does: stop the compiler from reporting useless warnings.\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"// then include this file where all our macros are defined. It's really important to do it first because\r\n"
"// it's where we do all the compiler/OS/arch detections and define most defaults.\r\n"
"#include \"src/Core/util/Macros.h\"\r\n"
"\r\n"
"// This detects SSE/AVX/NEON/etc. and configure alignment settings\r\n"
"#include \"src/Core/util/ConfigureVectorization.h\"\r\n"
"\r\n"
"// We need cuda_runtime.h/hip_runtime.h to ensure that\r\n"
"// the EIGEN_USING_STD macro works properly on the device side\r\n"
"#if defined(EIGEN_CUDACC)\r\n"
"  #include <cuda_runtime.h>\r\n"
"#elif defined(EIGEN_HIPCC)\r\n"
"  #include <hip/hip_runtime.h>\r\n"
"#endif\r\n"
"\r\n"
"\r\n"
"#ifdef EIGEN_EXCEPTIONS\r\n"
"  #include <new>\r\n"
"#endif\r\n"
"\r\n"
"// Disable the ipa-cp-clone optimization flag with MinGW 6.x or newer (enabled by default with -O3)\r\n"
"// See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=556 for details.\r\n"
"#if EIGEN_COMP_MINGW && EIGEN_GNUC_AT_LEAST(4,6) && EIGEN_GNUC_AT_MOST(5,5)\r\n"
"  #pragma GCC optimize (\"-fno-ipa-cp-clone\")\r\n"
"#endif\r\n"
"\r\n"
"// Prevent ICC from specializing std::complex operators that silently fail\r\n"
"// on device. This allows us to use our own device-compatible specializations\r\n"
"// instead.\r\n"
"#if defined(EIGEN_COMP_ICC) && defined(EIGEN_GPU_COMPILE_PHASE) \\\r\n"
"    && !defined(_OVERRIDE_COMPLEX_SPECIALIZATION_)\r\n"
"#define _OVERRIDE_COMPLEX_SPECIALIZATION_ 1\r\n"
"#endif\r\n"
"#include <complex>\r\n"
"\r\n"
"// this include file manages BLAS and MKL related macros\r\n"
"// and inclusion of their respective header files\r\n"
"#include \"src/Core/util/MKL_support.h\"\r\n"
"\r\n"
"\r\n"
"#if defined(EIGEN_HAS_CUDA_FP16) || defined(EIGEN_HAS_HIP_FP16)\r\n"
"  #define EIGEN_HAS_GPU_FP16\r\n"
"#endif\r\n"
"\r\n"
"#if defined(EIGEN_HAS_CUDA_BF16) || defined(EIGEN_HAS_HIP_BF16)\r\n"
"  #define EIGEN_HAS_GPU_BF16\r\n"
"#endif\r\n"
"\r\n"
"#if (defined _OPENMP) && (!defined EIGEN_DONT_PARALLELIZE)\r\n"
"  #define EIGEN_HAS_OPENMP\r\n"
"#endif\r\n"
"\r\n"
"#ifdef EIGEN_HAS_OPENMP\r\n"
"#include <omp.h>\r\n"
"#endif\r\n"
"\r\n"
"// MSVC for windows mobile does not have the errno.h file\r\n"
"#if !(EIGEN_COMP_MSVC && EIGEN_OS_WINCE) && !EIGEN_COMP_ARM\r\n"
"#define EIGEN_HAS_ERRNO\r\n"
"#endif\r\n"
"\r\n"
"#ifdef EIGEN_HAS_ERRNO\r\n"
"#include <cerrno>\r\n"
"#endif\r\n"
"#include <cstddef>\r\n"
"#include <cstdlib>\r\n"
"#include <cmath>\r\n"
"#include <cassert>\r\n"
"#include <functional>\r\n"
"#include <sstream>\r\n"
"#ifndef EIGEN_NO_IO\r\n"
"  #include <iosfwd>\r\n"
"#endif\r\n"
"#include <cstring>\r\n"
"#include <string>\r\n"
"#include <limits>\r\n"
"#include <climits> // for CHAR_BIT\r\n"
"// for min/max:\r\n"
"#include <algorithm>\r\n"
"\r\n"
"#if EIGEN_HAS_CXX11\r\n"
"#include <array>\r\n"
"#endif\r\n"
"\r\n"
"// for std::is_nothrow_move_assignable\r\n"
"#ifdef EIGEN_INCLUDE_TYPE_TRAITS\r\n"
"#include <type_traits>\r\n"
"#endif\r\n"
"\r\n"
"// for outputting debug info\r\n"
"#ifdef EIGEN_DEBUG_ASSIGN\r\n"
"#include <iostream>\r\n"
"#endif\r\n"
"\r\n"
"// required for __cpuid, needs to be included after cmath\r\n"
"#if EIGEN_COMP_MSVC && EIGEN_ARCH_i386_OR_x86_64 && !EIGEN_OS_WINCE\r\n"
"  #include <intrin.h>\r\n"
"#endif\r\n"
"\r\n"
"#if defined(EIGEN_USE_SYCL)\r\n"
"  #undef min\r\n"
"  #undef max\r\n"
"  #undef isnan\r\n"
"  #undef isinf\r\n"
"  #undef isfinite\r\n"
"  #include <CL/sycl.hpp>\r\n"
"  #include <map>\r\n"
"  #include <memory>\r\n"
"  #include <utility>\r\n"
"  #include <thread>\r\n"
"  #ifndef EIGEN_SYCL_LOCAL_THREAD_DIM0\r\n"
"  #define EIGEN_SYCL_LOCAL_THREAD_DIM0 16\r\n"
"  #endif\r\n"
"  #ifndef EIGEN_SYCL_LOCAL_THREAD_DIM1\r\n"
"  #define EIGEN_SYCL_LOCAL_THREAD_DIM1 16\r\n"
"  #endif\r\n"
"#endif\r\n"
"\r\n"
"\r\n"
"#if defined EIGEN2_SUPPORT_STAGE40_FULL_EIGEN3_STRICTNESS || defined EIGEN2_SUPPORT_STAGE30_FULL_EIGEN3_API || defined EIGEN2_SUPPORT_STAGE20_RESOLVE_API_CONFLICTS || defined EIGEN2_SUPPORT_STAGE10_FULL_EIGEN2_API || defined EIGEN2_SUPPORT\r\n"
"// This will generate an error message:\r\n"
"#error Eigen2-support is only available up to version 3.2. Please go to \"http://eigen.tuxfamily.org/index.php?title=Eigen2\" for further information\r\n"
"#endif\r\n"
"\r\n"
"namespace Eigen {\r\n"
"\r\n"
"// we use size_t frequently and we'll never remember to prepend it with std:: every time just to\r\n"
"// ensure QNX/QCC support\r\n"
"using std::size_t;\r\n"
"// gcc 4.6.0 wants std:: for ptrdiff_t\r\n"
"using std::ptrdiff_t;\r\n"
"\r\n"
"}\r\n"
"\r\n"
"/** \\defgroup Core_Module Core module\r\n"
"  * This is the main module of Eigen providing dense matrix and vector support\r\n"
"  * (both fixed and dynamic size) with all the features corresponding to a BLAS library\r\n"
"  * and much more...\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Core>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/Core/util/Constants.h\"\r\n"
"#include \"src/Core/util/Meta.h\"\r\n"
"#include \"src/Core/util/ForwardDeclarations.h\"\r\n"
"#include \"src/Core/util/StaticAssert.h\"\r\n"
"#include \"src/Core/util/XprHelper.h\"\r\n"
"#include \"src/Core/util/Memory.h\"\r\n"
"#include \"src/Core/util/IntegralConstant.h\"\r\n"
"#include \"src/Core/util/SymbolicIndex.h\"\r\n"
"\r\n"
"#include \"src/Core/NumTraits.h\"\r\n"
"#include \"src/Core/MathFunctions.h\"\r\n"
"#include \"src/Core/GenericPacketMath.h\"\r\n"
"#include \"src/Core/MathFunctionsImpl.h\"\r\n"
"#include \"src/Core/arch/Default/ConjHelper.h\"\r\n"
"// Generic half float support\r\n"
"#include \"src/Core/arch/Default/Half.h\"\r\n"
"#include \"src/Core/arch/Default/BFloat16.h\"\r\n"
"#include \"src/Core/arch/Default/TypeCasting.h\"\r\n"
"#include \"src/Core/arch/Default/GenericPacketMathFunctionsFwd.h\"\r\n"
"\r\n"
"#if defined EIGEN_VECTORIZE_AVX512\r\n"
"  #include \"src/Core/arch/SSE/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/SSE/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/SSE/Complex.h\"\r\n"
"  #include \"src/Core/arch/AVX/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/AVX/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/AVX/Complex.h\"\r\n"
"  #include \"src/Core/arch/AVX512/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/AVX512/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/AVX512/Complex.h\"\r\n"
"  #include \"src/Core/arch/SSE/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/AVX/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/AVX512/MathFunctions.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_AVX\r\n"
"  // Use AVX for floats and doubles, SSE for integers\r\n"
"  #include \"src/Core/arch/SSE/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/SSE/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/SSE/Complex.h\"\r\n"
"  #include \"src/Core/arch/AVX/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/AVX/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/AVX/Complex.h\"\r\n"
"  #include \"src/Core/arch/SSE/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/AVX/MathFunctions.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_SSE\r\n"
"  #include \"src/Core/arch/SSE/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/SSE/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/SSE/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/SSE/Complex.h\"\r\n"
"#elif defined(EIGEN_VECTORIZE_ALTIVEC) || defined(EIGEN_VECTORIZE_VSX)\r\n"
"  #include \"src/Core/arch/AltiVec/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/AltiVec/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/AltiVec/Complex.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_NEON\r\n"
"  #include \"src/Core/arch/NEON/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/NEON/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/NEON/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/NEON/Complex.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_SVE\r\n"
"  #include \"src/Core/arch/SVE/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/SVE/TypeCasting.h\"\r\n"
"  #include \"src/Core/arch/SVE/MathFunctions.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_ZVECTOR\r\n"
"  #include \"src/Core/arch/ZVector/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/ZVector/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/ZVector/Complex.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_MSA\r\n"
"  #include \"src/Core/arch/MSA/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/MSA/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/MSA/Complex.h\"\r\n"
"#endif\r\n"
"\r\n"
"#if defined EIGEN_VECTORIZE_GPU\r\n"
"  #include \"src/Core/arch/GPU/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/GPU/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/GPU/TypeCasting.h\"\r\n"
"#endif\r\n"
"\r\n"
"#if defined(EIGEN_USE_SYCL)\r\n"
"  #include \"src/Core/arch/SYCL/SyclMemoryModel.h\"\r\n"
"  #include \"src/Core/arch/SYCL/InteropHeaders.h\"\r\n"
"#if !defined(EIGEN_DONT_VECTORIZE_SYCL)\r\n"
"  #include \"src/Core/arch/SYCL/PacketMath.h\"\r\n"
"  #include \"src/Core/arch/SYCL/MathFunctions.h\"\r\n"
"  #include \"src/Core/arch/SYCL/TypeCasting.h\"\r\n"
"#endif\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/arch/Default/Settings.h\"\r\n"
"// This file provides generic implementations valid for scalar as well\r\n"
"#include \"src/Core/arch/Default/GenericPacketMathFunctions.h\"\r\n"
"\r\n"
"#include \"src/Core/functors/TernaryFunctors.h\"\r\n"
"#include \"src/Core/functors/BinaryFunctors.h\"\r\n"
"#include \"src/Core/functors/UnaryFunctors.h\"\r\n"
"#include \"src/Core/functors/NullaryFunctors.h\"\r\n"
"#include \"src/Core/functors/StlFunctors.h\"\r\n"
"#include \"src/Core/functors/AssignmentFunctors.h\"\r\n"
"\r\n"
"// Specialized functors to enable the processing of complex numbers\r\n"
"// on CUDA devices\r\n"
"#ifdef EIGEN_CUDACC\r\n"
"#include \"src/Core/arch/CUDA/Complex.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/IndexedViewHelper.h\"\r\n"
"#include \"src/Core/util/ReshapedHelper.h\"\r\n"
"#include \"src/Core/ArithmeticSequence.h\"\r\n"
"#ifndef EIGEN_NO_IO\r\n"
"  #include \"src/Core/IO.h\"\r\n"
"#endif\r\n"
"#include \"src/Core/DenseCoeffsBase.h\"\r\n"
"#include \"src/Core/DenseBase.h\"\r\n"
"#include \"src/Core/MatrixBase.h\"\r\n"
"#include \"src/Core/EigenBase.h\"\r\n"
"\r\n"
"#include \"src/Core/Product.h\"\r\n"
"#include \"src/Core/CoreEvaluators.h\"\r\n"
"#include \"src/Core/AssignEvaluator.h\"\r\n"
"\r\n"
"#ifndef EIGEN_PARSED_BY_DOXYGEN // work around Doxygen bug triggered by Assign.h r814874\r\n"
"                                // at least confirmed with Doxygen 1.5.5 and 1.5.6\r\n"
"  #include \"src/Core/Assign.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/ArrayBase.h\"\r\n"
"#include \"src/Core/util/BlasUtil.h\"\r\n"
"#include \"src/Core/DenseStorage.h\"\r\n"
"#include \"src/Core/NestByValue.h\"\r\n"
"\r\n"
"// #include \"src/Core/ForceAlignedAccess.h\"\r\n"
"\r\n"
"#include \"src/Core/ReturnByValue.h\"\r\n"
"#include \"src/Core/NoAlias.h\"\r\n"
"#include \"src/Core/PlainObjectBase.h\"\r\n"
"#include \"src/Core/Matrix.h\"\r\n"
"#include \"src/Core/Array.h\"\r\n"
"#include \"src/Core/CwiseTernaryOp.h\"\r\n"
"#include \"src/Core/CwiseBinaryOp.h\"\r\n"
"#include \"src/Core/CwiseUnaryOp.h\"\r\n"
"#include \"src/Core/CwiseNullaryOp.h\"\r\n"
"#include \"src/Core/CwiseUnaryView.h\"\r\n"
"#include \"src/Core/SelfCwiseBinaryOp.h\"\r\n"
"#include \"src/Core/Dot.h\"\r\n"
"#include \"src/Core/StableNorm.h\"\r\n"
"#include \"src/Core/Stride.h\"\r\n"
"#include \"src/Core/MapBase.h\"\r\n"
"#include \"src/Core/Map.h\"\r\n"
"#include \"src/Core/Ref.h\"\r\n"
"#include \"src/Core/Block.h\"\r\n"
"#include \"src/Core/VectorBlock.h\"\r\n"
"#include \"src/Core/IndexedView.h\"\r\n"
"#include \"src/Core/Reshaped.h\"\r\n"
"#include \"src/Core/Transpose.h\"\r\n"
"#include \"src/Core/DiagonalMatrix.h\"\r\n"
"#include \"src/Core/Diagonal.h\"\r\n"
"#include \"src/Core/DiagonalProduct.h\"\r\n"
"#include \"src/Core/Redux.h\"\r\n"
"#include \"src/Core/Visitor.h\"\r\n"
"#include \"src/Core/Fuzzy.h\"\r\n"
"#include \"src/Core/Swap.h\"\r\n"
"#include \"src/Core/CommaInitializer.h\"\r\n"
"#include \"src/Core/GeneralProduct.h\"\r\n"
"#include \"src/Core/Solve.h\"\r\n"
"#include \"src/Core/Inverse.h\"\r\n"
"#include \"src/Core/SolverBase.h\"\r\n"
"#include \"src/Core/PermutationMatrix.h\"\r\n"
"#include \"src/Core/Transpositions.h\"\r\n"
"#include \"src/Core/TriangularMatrix.h\"\r\n"
"#include \"src/Core/SelfAdjointView.h\"\r\n"
"#include \"src/Core/products/GeneralBlockPanelKernel.h\"\r\n"
"#include \"src/Core/products/Parallelizer.h\"\r\n"
"#include \"src/Core/ProductEvaluators.h\"\r\n"
"#include \"src/Core/products/GeneralMatrixVector.h\"\r\n"
"#include \"src/Core/products/GeneralMatrixMatrix.h\"\r\n"
"#include \"src/Core/SolveTriangular.h\"\r\n"
"#include \"src/Core/products/GeneralMatrixMatrixTriangular.h\"\r\n"
"#include \"src/Core/products/SelfadjointMatrixVector.h\"\r\n"
"#include \"src/Core/products/SelfadjointMatrixMatrix.h\"\r\n"
"#include \"src/Core/products/SelfadjointProduct.h\"\r\n"
"#include \"src/Core/products/SelfadjointRank2Update.h\"\r\n"
"#include \"src/Core/products/TriangularMatrixVector.h\"\r\n"
"#include \"src/Core/products/TriangularMatrixMatrix.h\"\r\n"
"#include \"src/Core/products/TriangularSolverMatrix.h\"\r\n"
"#include \"src/Core/products/TriangularSolverVector.h\"\r\n"
"#include \"src/Core/BandMatrix.h\"\r\n"
"#include \"src/Core/CoreIterators.h\"\r\n"
"#include \"src/Core/ConditionEstimator.h\"\r\n"
"\r\n"
"#if defined(EIGEN_VECTORIZE_ALTIVEC) || defined(EIGEN_VECTORIZE_VSX)\r\n"
"  #include \"src/Core/arch/AltiVec/MatrixProduct.h\"\r\n"
"#elif defined EIGEN_VECTORIZE_NEON\r\n"
"  #include \"src/Core/arch/NEON/GeneralBlockPanelKernel.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/BooleanRedux.h\"\r\n"
"#include \"src/Core/Select.h\"\r\n"
"#include \"src/Core/VectorwiseOp.h\"\r\n"
"#include \"src/Core/PartialReduxEvaluator.h\"\r\n"
"#include \"src/Core/Random.h\"\r\n"
"#include \"src/Core/Replicate.h\"\r\n"
"#include \"src/Core/Reverse.h\"\r\n"
"#include \"src/Core/ArrayWrapper.h\"\r\n"
"#include \"src/Core/StlIterators.h\"\r\n"
"\r\n"
"#ifdef EIGEN_USE_BLAS\r\n"
"#include \"src/Core/products/GeneralMatrixMatrix_BLAS.h\"\r\n"
"#include \"src/Core/products/GeneralMatrixVector_BLAS.h\"\r\n"
"#include \"src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h\"\r\n"
"#include \"src/Core/products/SelfadjointMatrixMatrix_BLAS.h\"\r\n"
"#include \"src/Core/products/SelfadjointMatrixVector_BLAS.h\"\r\n"
"#include \"src/Core/products/TriangularMatrixMatrix_BLAS.h\"\r\n"
"#include \"src/Core/products/TriangularMatrixVector_BLAS.h\"\r\n"
"#include \"src/Core/products/TriangularSolverMatrix_BLAS.h\"\r\n"
"#endif // EIGEN_USE_BLAS\r\n"
"\r\n"
"#ifdef EIGEN_USE_MKL_VML\r\n"
"#include \"src/Core/Assign_MKL.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/GlobalFunctions.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_CORE_H\r\n";

const char* Core = (const char*) temp_binary_data_2;

//================== Dense ==================
static const unsigned char temp_binary_data_3[] =
"#include \"Core\"\r\n"
"#include \"LU\"\r\n"
"#include \"Cholesky\"\r\n"
"#include \"QR\"\r\n"
"#include \"SVD\"\r\n"
"#include \"Geometry\"\r\n"
"#include \"Eigenvalues\"\r\n";

const char* Dense = (const char*) temp_binary_data_3;

//================== Eigen ==================
static const unsigned char temp_binary_data_4[] =
"#include \"Dense\"\r\n"
"#include \"Sparse\"\r\n";

const char* Eigen = (const char*) temp_binary_data_4;

//================== Eigenvalues ==================
static const unsigned char temp_binary_data_5[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_EIGENVALUES_MODULE_H\r\n"
"#define EIGEN_EIGENVALUES_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"Cholesky\"\r\n"
"#include \"Jacobi\"\r\n"
"#include \"Householder\"\r\n"
"#include \"LU\"\r\n"
"#include \"Geometry\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup Eigenvalues_Module Eigenvalues module\r\n"
"  *\r\n"
"  *\r\n"
"  *\r\n"
"  * This module mainly provides various eigenvalue solvers.\r\n"
"  * This module also provides some MatrixBase methods, including:\r\n"
"  *  - MatrixBase::eigenvalues(),\r\n"
"  *  - MatrixBase::operatorNorm()\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Eigenvalues>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/misc/RealSvd2x2.h\"\r\n"
"#include \"src/Eigenvalues/Tridiagonalization.h\"\r\n"
"#include \"src/Eigenvalues/RealSchur.h\"\r\n"
"#include \"src/Eigenvalues/EigenSolver.h\"\r\n"
"#include \"src/Eigenvalues/SelfAdjointEigenSolver.h\"\r\n"
"#include \"src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h\"\r\n"
"#include \"src/Eigenvalues/HessenbergDecomposition.h\"\r\n"
"#include \"src/Eigenvalues/ComplexSchur.h\"\r\n"
"#include \"src/Eigenvalues/ComplexEigenSolver.h\"\r\n"
"#include \"src/Eigenvalues/RealQZ.h\"\r\n"
"#include \"src/Eigenvalues/GeneralizedEigenSolver.h\"\r\n"
"#include \"src/Eigenvalues/MatrixBaseEigenvalues.h\"\r\n"
"#ifdef EIGEN_USE_LAPACKE\r\n"
"#ifdef EIGEN_USE_MKL\r\n"
"#include \"mkl_lapacke.h\"\r\n"
"#else\r\n"
"#include \"src/misc/lapacke.h\"\r\n"
"#endif\r\n"
"#include \"src/Eigenvalues/RealSchur_LAPACKE.h\"\r\n"
"#include \"src/Eigenvalues/ComplexSchur_LAPACKE.h\"\r\n"
"#include \"src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_EIGENVALUES_MODULE_H\r\n";

const char* Eigenvalues = (const char*) temp_binary_data_5;

//================== Geometry ==================
static const unsigned char temp_binary_data_6[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_GEOMETRY_MODULE_H\r\n"
"#define EIGEN_GEOMETRY_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"SVD\"\r\n"
"#include \"LU\"\r\n"
"#include <limits>\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup Geometry_Module Geometry module\r\n"
"  *\r\n"
"  * This module provides support for:\r\n"
"  *  - fixed-size homogeneous transformations\r\n"
"  *  - translation, scaling, 2D and 3D rotations\r\n"
"  *  - \\link Quaternion quaternions \\endlink\r\n"
"  *  - cross products (\\ref MatrixBase::cross, \\ref MatrixBase::cross3)\r\n"
"  *  - orthognal vector generation (\\ref MatrixBase::unitOrthogonal)\r\n"
"  *  - some linear components: \\link ParametrizedLine parametrized-lines \\endlink and \\link Hyperplane hyperplanes \\endlink\r\n"
"  *  - \\link AlignedBox axis aligned bounding boxes \\endlink\r\n"
"  *  - \\link umeyama least-square transformation fitting \\endlink\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Geometry>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/Geometry/OrthoMethods.h\"\r\n"
"#include \"src/Geometry/EulerAngles.h\"\r\n"
"\r\n"
"#include \"src/Geometry/Homogeneous.h\"\r\n"
"#include \"src/Geometry/RotationBase.h\"\r\n"
"#include \"src/Geometry/Rotation2D.h\"\r\n"
"#include \"src/Geometry/Quaternion.h\"\r\n"
"#include \"src/Geometry/AngleAxis.h\"\r\n"
"#include \"src/Geometry/Transform.h\"\r\n"
"#include \"src/Geometry/Translation.h\"\r\n"
"#include \"src/Geometry/Scaling.h\"\r\n"
"#include \"src/Geometry/Hyperplane.h\"\r\n"
"#include \"src/Geometry/ParametrizedLine.h\"\r\n"
"#include \"src/Geometry/AlignedBox.h\"\r\n"
"#include \"src/Geometry/Umeyama.h\"\r\n"
"\r\n"
"// Use the SSE optimized version whenever possible.\r\n"
"#if (defined EIGEN_VECTORIZE_SSE) || (defined EIGEN_VECTORIZE_NEON)\r\n"
"#include \"src/Geometry/arch/Geometry_SIMD.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_GEOMETRY_MODULE_H\r\n";

const char* Geometry = (const char*) temp_binary_data_6;

//================== Householder ==================
static const unsigned char temp_binary_data_7[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_HOUSEHOLDER_MODULE_H\r\n"
"#define EIGEN_HOUSEHOLDER_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup Householder_Module Householder module\r\n"
"  * This module provides Householder transformations.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Householder>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/Householder/Householder.h\"\r\n"
"#include \"src/Householder/HouseholderSequence.h\"\r\n"
"#include \"src/Householder/BlockHouseholder.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_HOUSEHOLDER_MODULE_H\r\n";

const char* Householder = (const char*) temp_binary_data_7;

//================== IterativeLinearSolvers ==================
static const unsigned char temp_binary_data_8[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_ITERATIVELINEARSOLVERS_MODULE_H\r\n"
"#define EIGEN_ITERATIVELINEARSOLVERS_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"#include \"OrderingMethods\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \r\n"
"  * \\defgroup IterativeLinearSolvers_Module IterativeLinearSolvers module\r\n"
"  *\r\n"
"  * This module currently provides iterative methods to solve problems of the form \\c A \\c x = \\c b, where \\c A is a squared matrix, usually very large and sparse.\r\n"
"  * Those solvers are accessible via the following classes:\r\n"
"  *  - ConjugateGradient for selfadjoint (hermitian) matrices,\r\n"
"  *  - LeastSquaresConjugateGradient for rectangular least-square problems,\r\n"
"  *  - BiCGSTAB for general square matrices.\r\n"
"  *\r\n"
"  * These iterative solvers are associated with some preconditioners:\r\n"
"  *  - IdentityPreconditioner - not really useful\r\n"
"  *  - DiagonalPreconditioner - also called Jacobi preconditioner, work very well on diagonal dominant matrices.\r\n"
"  *  - IncompleteLUT - incomplete LU factorization with dual thresholding\r\n"
"  *\r\n"
"  * Such problems can also be solved using the direct sparse decomposition modules: SparseCholesky, CholmodSupport, UmfPackSupport, SuperLUSupport.\r\n"
"  *\r\n"
"    \\code\r\n"
"    #include <Eigen/IterativeLinearSolvers>\r\n"
"    \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/IterativeLinearSolvers/SolveWithGuess.h\"\r\n"
"#include \"src/IterativeLinearSolvers/IterativeSolverBase.h\"\r\n"
"#include \"src/IterativeLinearSolvers/BasicPreconditioners.h\"\r\n"
"#include \"src/IterativeLinearSolvers/ConjugateGradient.h\"\r\n"
"#include \"src/IterativeLinearSolvers/LeastSquareConjugateGradient.h\"\r\n"
"#include \"src/IterativeLinearSolvers/BiCGSTAB.h\"\r\n"
"#include \"src/IterativeLinearSolvers/IncompleteLUT.h\"\r\n"
"#include \"src/IterativeLinearSolvers/IncompleteCholesky.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_ITERATIVELINEARSOLVERS_MODULE_H\r\n";

const char* IterativeLinearSolvers = (const char*) temp_binary_data_8;

//================== Jacobi ==================
static const unsigned char temp_binary_data_9[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_JACOBI_MODULE_H\r\n"
"#define EIGEN_JACOBI_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup Jacobi_Module Jacobi module\r\n"
"  * This module provides Jacobi and Givens rotations.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/Jacobi>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In addition to listed classes, it defines the two following MatrixBase methods to apply a Jacobi or Givens rotation:\r\n"
"  *  - MatrixBase::applyOnTheLeft()\r\n"
"  *  - MatrixBase::applyOnTheRight().\r\n"
"  */\r\n"
"\r\n"
"#include \"src/Jacobi/Jacobi.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_JACOBI_MODULE_H\r\n"
"\r\n";

const char* Jacobi = (const char*) temp_binary_data_9;

//================== KLUSupport ==================
static const unsigned char temp_binary_data_10[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_KLUSUPPORT_MODULE_H\r\n"
"#define EIGEN_KLUSUPPORT_MODULE_H\r\n"
"\r\n"
"#include <Eigen/SparseCore>\r\n"
"\r\n"
"#include <Eigen/src/Core/util/DisableStupidWarnings.h>\r\n"
"\r\n"
"extern \"C\" {\r\n"
"#include <btf.h>\r\n"
"#include <klu.h>\r\n"
"   }\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup KLUSupport_Module KLUSupport module\r\n"
"  *\r\n"
"  * This module provides an interface to the KLU library which is part of the <a href=\"http://www.suitesparse.com\">suitesparse</a> package.\r\n"
"  * It provides the following factorization class:\r\n"
"  * - class KLU: a sparse LU factorization, well-suited for circuit simulation.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/KLUSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the klu and btf headers must be accessible from the include paths, and your binary must be linked to the klu library and its dependencies.\r\n"
"  * The dependencies depend on how umfpack has been compiled.\r\n"
"  * For a cmake based project, you can use our FindKLU.cmake module to help you in this task.\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/KLUSupport/KLUSupport.h\"\r\n"
"\r\n"
"#include <Eigen/src/Core/util/ReenableStupidWarnings.h>\r\n"
"\r\n"
"#endif // EIGEN_KLUSUPPORT_MODULE_H\r\n";

const char* KLUSupport = (const char*) temp_binary_data_10;

//================== LU ==================
static const unsigned char temp_binary_data_11[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_LU_MODULE_H\r\n"
"#define EIGEN_LU_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup LU_Module LU module\r\n"
"  * This module includes %LU decomposition and related notions such as matrix inversion and determinant.\r\n"
"  * This module defines the following MatrixBase methods:\r\n"
"  *  - MatrixBase::inverse()\r\n"
"  *  - MatrixBase::determinant()\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/LU>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/misc/Kernel.h\"\r\n"
"#include \"src/misc/Image.h\"\r\n"
"#include \"src/LU/FullPivLU.h\"\r\n"
"#include \"src/LU/PartialPivLU.h\"\r\n"
"#ifdef EIGEN_USE_LAPACKE\r\n"
"#ifdef EIGEN_USE_MKL\r\n"
"#include \"mkl_lapacke.h\"\r\n"
"#else\r\n"
"#include \"src/misc/lapacke.h\"\r\n"
"#endif\r\n"
"#include \"src/LU/PartialPivLU_LAPACKE.h\"\r\n"
"#endif\r\n"
"#include \"src/LU/Determinant.h\"\r\n"
"#include \"src/LU/InverseImpl.h\"\r\n"
"\r\n"
"#if defined EIGEN_VECTORIZE_SSE || defined EIGEN_VECTORIZE_NEON\r\n"
"  #include \"src/LU/arch/InverseSize4.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_LU_MODULE_H\r\n";

const char* LU = (const char*) temp_binary_data_11;

//================== MetisSupport ==================
static const unsigned char temp_binary_data_12[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_METISSUPPORT_MODULE_H\r\n"
"#define EIGEN_METISSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"extern \"C\" {\r\n"
"#include <metis.h>\r\n"
"}\r\n"
"\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup MetisSupport_Module MetisSupport module\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/MetisSupport>\r\n"
"  * \\endcode\r\n"
"  * This module defines an interface to the METIS reordering package (http://glaros.dtc.umn.edu/gkhome/views/metis). \r\n"
"  * It can be used just as any other built-in method as explained in \\link OrderingMethods_Module here. \\endlink\r\n"
"  */\r\n"
"\r\n"
"\r\n"
"#include \"src/MetisSupport/MetisSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_METISSUPPORT_MODULE_H\r\n";

const char* MetisSupport = (const char*) temp_binary_data_12;

//================== OrderingMethods ==================
static const unsigned char temp_binary_data_13[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_ORDERINGMETHODS_MODULE_H\r\n"
"#define EIGEN_ORDERINGMETHODS_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \r\n"
"  * \\defgroup OrderingMethods_Module OrderingMethods module\r\n"
"  *\r\n"
"  * This module is currently for internal use only\r\n"
"  * \r\n"
"  * It defines various built-in and external ordering methods for sparse matrices. \r\n"
"  * They are typically used to reduce the number of elements during \r\n"
"  * the sparse matrix decomposition (LLT, LU, QR).\r\n"
"  * Precisely, in a preprocessing step, a permutation matrix P is computed using \r\n"
"  * those ordering methods and applied to the columns of the matrix. \r\n"
"  * Using for instance the sparse Cholesky decomposition, it is expected that \r\n"
"  * the nonzeros elements in LLT(A*P) will be much smaller than that in LLT(A).\r\n"
"  * \r\n"
"  * \r\n"
"  * Usage : \r\n"
"  * \\code\r\n"
"  * #include <Eigen/OrderingMethods>\r\n"
"  * \\endcode\r\n"
"  * \r\n"
"  * A simple usage is as a template parameter in the sparse decomposition classes : \r\n"
"  * \r\n"
"  * \\code \r\n"
"  * SparseLU<MatrixType, COLAMDOrdering<int> > solver;\r\n"
"  * \\endcode \r\n"
"  * \r\n"
"  * \\code \r\n"
"  * SparseQR<MatrixType, COLAMDOrdering<int> > solver;\r\n"
"  * \\endcode\r\n"
"  * \r\n"
"  * It is possible as well to call directly a particular ordering method for your own purpose, \r\n"
"  * \\code \r\n"
"  * AMDOrdering<int> ordering;\r\n"
"  * PermutationMatrix<Dynamic, Dynamic, int> perm;\r\n"
"  * SparseMatrix<double> A; \r\n"
"  * //Fill the matrix ...\r\n"
"  * \r\n"
"  * ordering(A, perm); // Call AMD\r\n"
"  * \\endcode\r\n"
"  * \r\n"
"  * \\note Some of these methods (like AMD or METIS), need the sparsity pattern \r\n"
"  * of the input matrix to be symmetric. When the matrix is structurally unsymmetric, \r\n"
"  * Eigen computes internally the pattern of \\f$A^T*A\\f$ before calling the method.\r\n"
"  * If your matrix is already symmetric (at leat in structure), you can avoid that\r\n"
"  * by calling the method with a SelfAdjointView type.\r\n"
"  * \r\n"
"  * \\code\r\n"
"  *  // Call the ordering on the pattern of the lower triangular matrix A\r\n"
"  * ordering(A.selfadjointView<Lower>(), perm);\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/OrderingMethods/Amd.h\"\r\n"
"#include \"src/OrderingMethods/Ordering.h\"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_ORDERINGMETHODS_MODULE_H\r\n";

const char* OrderingMethods = (const char*) temp_binary_data_13;

//================== PardisoSupport ==================
static const unsigned char temp_binary_data_14[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_PARDISOSUPPORT_MODULE_H\r\n"
"#define EIGEN_PARDISOSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"#include <mkl_pardiso.h>\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup PardisoSupport_Module PardisoSupport module\r\n"
"  *\r\n"
"  * This module brings support for the Intel(R) MKL PARDISO direct sparse solvers.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/PardisoSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the MKL headers must be accessible from the include paths, and your binary must be linked to the MKL library and its dependencies.\r\n"
"  * See this \\ref TopicUsingIntelMKL \"page\" for more information on MKL-Eigen integration.\r\n"
"  * \r\n"
"  */\r\n"
"\r\n"
"#include \"src/PardisoSupport/PardisoSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_PARDISOSUPPORT_MODULE_H\r\n";

const char* PardisoSupport = (const char*) temp_binary_data_14;

//================== PaStiXSupport ==================
static const unsigned char temp_binary_data_15[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_PASTIXSUPPORT_MODULE_H\r\n"
"#define EIGEN_PASTIXSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"extern \"C\" {\r\n"
"#include <pastix_nompi.h>\r\n"
"#include <pastix.h>\r\n"
"}\r\n"
"\r\n"
"#ifdef complex\r\n"
"#undef complex\r\n"
"#endif\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup PaStiXSupport_Module PaStiXSupport module\r\n"
"  * \r\n"
"  * This module provides an interface to the <a href=\"http://pastix.gforge.inria.fr/\">PaSTiX</a> library.\r\n"
"  * PaSTiX is a general \\b supernodal, \\b parallel and \\b opensource sparse solver.\r\n"
"  * It provides the two following main factorization classes:\r\n"
"  * - class PastixLLT : a supernodal, parallel LLt Cholesky factorization.\r\n"
"  * - class PastixLDLT: a supernodal, parallel LDLt Cholesky factorization.\r\n"
"  * - class PastixLU : a supernodal, parallel LU factorization (optimized for a symmetric pattern).\r\n"
"  * \r\n"
"  * \\code\r\n"
"  * #include <Eigen/PaStiXSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the PaSTiX headers must be accessible from the include paths, and your binary must be linked to the PaSTiX library and its dependencies.\r\n"
"  * This wrapper resuires PaStiX version 5.x compiled without MPI support.\r\n"
"  * The dependencies depend on how PaSTiX has been compiled.\r\n"
"  * For a cmake based project, you can use our FindPaSTiX.cmake module to help you in this task.\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/PaStiXSupport/PaStiXSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_PASTIXSUPPORT_MODULE_H\r\n";

const char* PaStiXSupport = (const char*) temp_binary_data_15;

//================== QR ==================
static const unsigned char temp_binary_data_16[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_QR_MODULE_H\r\n"
"#define EIGEN_QR_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"Cholesky\"\r\n"
"#include \"Jacobi\"\r\n"
"#include \"Householder\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup QR_Module QR module\r\n"
"  *\r\n"
"  *\r\n"
"  *\r\n"
"  * This module provides various QR decompositions\r\n"
"  * This module also provides some MatrixBase methods, including:\r\n"
"  *  - MatrixBase::householderQr()\r\n"
"  *  - MatrixBase::colPivHouseholderQr()\r\n"
"  *  - MatrixBase::fullPivHouseholderQr()\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/QR>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/QR/HouseholderQR.h\"\r\n"
"#include \"src/QR/FullPivHouseholderQR.h\"\r\n"
"#include \"src/QR/ColPivHouseholderQR.h\"\r\n"
"#include \"src/QR/CompleteOrthogonalDecomposition.h\"\r\n"
"#ifdef EIGEN_USE_LAPACKE\r\n"
"#ifdef EIGEN_USE_MKL\r\n"
"#include \"mkl_lapacke.h\"\r\n"
"#else\r\n"
"#include \"src/misc/lapacke.h\"\r\n"
"#endif\r\n"
"#include \"src/QR/HouseholderQR_LAPACKE.h\"\r\n"
"#include \"src/QR/ColPivHouseholderQR_LAPACKE.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_QR_MODULE_H\r\n";

const char* QR = (const char*) temp_binary_data_16;

//================== QtAlignedMalloc ==================
static const unsigned char temp_binary_data_17[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_QTMALLOC_MODULE_H\r\n"
"#define EIGEN_QTMALLOC_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#if (!EIGEN_MALLOC_ALREADY_ALIGNED)\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"void *qMalloc(std::size_t size)\r\n"
"{\r\n"
"  return Eigen::internal::aligned_malloc(size);\r\n"
"}\r\n"
"\r\n"
"void qFree(void *ptr)\r\n"
"{\r\n"
"  Eigen::internal::aligned_free(ptr);\r\n"
"}\r\n"
"\r\n"
"void *qRealloc(void *ptr, std::size_t size)\r\n"
"{\r\n"
"  void* newPtr = Eigen::internal::aligned_malloc(size);\r\n"
"  std::memcpy(newPtr, ptr, size);\r\n"
"  Eigen::internal::aligned_free(ptr);\r\n"
"  return newPtr;\r\n"
"}\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif\r\n"
"\r\n"
"#endif // EIGEN_QTMALLOC_MODULE_H\r\n";

const char* QtAlignedMalloc = (const char*) temp_binary_data_17;

//================== Sparse ==================
static const unsigned char temp_binary_data_18[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPARSE_MODULE_H\r\n"
"#define EIGEN_SPARSE_MODULE_H\r\n"
"\r\n"
"/** \\defgroup Sparse_Module Sparse meta-module\r\n"
"  *\r\n"
"  * Meta-module including all related modules:\r\n"
"  * - \\ref SparseCore_Module\r\n"
"  * - \\ref OrderingMethods_Module\r\n"
"  * - \\ref SparseCholesky_Module\r\n"
"  * - \\ref SparseLU_Module\r\n"
"  * - \\ref SparseQR_Module\r\n"
"  * - \\ref IterativeLinearSolvers_Module\r\n"
"  *\r\n"
"    \\code\r\n"
"    #include <Eigen/Sparse>\r\n"
"    \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"#include \"OrderingMethods\"\r\n"
"#include \"SparseCholesky\"\r\n"
"#include \"SparseLU\"\r\n"
"#include \"SparseQR\"\r\n"
"#include \"IterativeLinearSolvers\"\r\n"
"\r\n"
"#endif // EIGEN_SPARSE_MODULE_H\r\n"
"\r\n";

const char* Sparse = (const char*) temp_binary_data_18;

//================== SparseCholesky ==================
static const unsigned char temp_binary_data_19[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2008-2013 Gael Guennebaud <gael.guennebaud@inria.fr>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPARSECHOLESKY_MODULE_H\r\n"
"#define EIGEN_SPARSECHOLESKY_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"#include \"OrderingMethods\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \r\n"
"  * \\defgroup SparseCholesky_Module SparseCholesky module\r\n"
"  *\r\n"
"  * This module currently provides two variants of the direct sparse Cholesky decomposition for selfadjoint (hermitian) matrices.\r\n"
"  * Those decompositions are accessible via the following classes:\r\n"
"  *  - SimplicialLLt,\r\n"
"  *  - SimplicialLDLt\r\n"
"  *\r\n"
"  * Such problems can also be solved using the ConjugateGradient solver from the IterativeLinearSolvers module.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/SparseCholesky>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/SparseCholesky/SimplicialCholesky.h\"\r\n"
"#include \"src/SparseCholesky/SimplicialCholesky_impl.h\"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_SPARSECHOLESKY_MODULE_H\r\n";

const char* SparseCholesky = (const char*) temp_binary_data_19;

//================== SparseCore ==================
static const unsigned char temp_binary_data_20[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPARSECORE_MODULE_H\r\n"
"#define EIGEN_SPARSECORE_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"#include <vector>\r\n"
"#include <map>\r\n"
"#include <cstdlib>\r\n"
"#include <cstring>\r\n"
"#include <algorithm>\r\n"
"\r\n"
"/** \r\n"
"  * \\defgroup SparseCore_Module SparseCore module\r\n"
"  *\r\n"
"  * This module provides a sparse matrix representation, and basic associated matrix manipulations\r\n"
"  * and operations.\r\n"
"  *\r\n"
"  * See the \\ref TutorialSparse \"Sparse tutorial\"\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/SparseCore>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * This module depends on: Core.\r\n"
"  */\r\n"
"\r\n"
"#include \"src/SparseCore/SparseUtil.h\"\r\n"
"#include \"src/SparseCore/SparseMatrixBase.h\"\r\n"
"#include \"src/SparseCore/SparseAssign.h\"\r\n"
"#include \"src/SparseCore/CompressedStorage.h\"\r\n"
"#include \"src/SparseCore/AmbiVector.h\"\r\n"
"#include \"src/SparseCore/SparseCompressedBase.h\"\r\n"
"#include \"src/SparseCore/SparseMatrix.h\"\r\n"
"#include \"src/SparseCore/SparseMap.h\"\r\n"
"#include \"src/SparseCore/MappedSparseMatrix.h\"\r\n"
"#include \"src/SparseCore/SparseVector.h\"\r\n"
"#include \"src/SparseCore/SparseRef.h\"\r\n"
"#include \"src/SparseCore/SparseCwiseUnaryOp.h\"\r\n"
"#include \"src/SparseCore/SparseCwiseBinaryOp.h\"\r\n"
"#include \"src/SparseCore/SparseTranspose.h\"\r\n"
"#include \"src/SparseCore/SparseBlock.h\"\r\n"
"#include \"src/SparseCore/SparseDot.h\"\r\n"
"#include \"src/SparseCore/SparseRedux.h\"\r\n"
"#include \"src/SparseCore/SparseView.h\"\r\n"
"#include \"src/SparseCore/SparseDiagonalProduct.h\"\r\n"
"#include \"src/SparseCore/ConservativeSparseSparseProduct.h\"\r\n"
"#include \"src/SparseCore/SparseSparseProductWithPruning.h\"\r\n"
"#include \"src/SparseCore/SparseProduct.h\"\r\n"
"#include \"src/SparseCore/SparseDenseProduct.h\"\r\n"
"#include \"src/SparseCore/SparseSelfAdjointView.h\"\r\n"
"#include \"src/SparseCore/SparseTriangularView.h\"\r\n"
"#include \"src/SparseCore/TriangularSolver.h\"\r\n"
"#include \"src/SparseCore/SparsePermutation.h\"\r\n"
"#include \"src/SparseCore/SparseFuzzy.h\"\r\n"
"#include \"src/SparseCore/SparseSolverBase.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_SPARSECORE_MODULE_H\r\n"
"\r\n";

const char* SparseCore = (const char*) temp_binary_data_20;

//================== SparseLU ==================
static const unsigned char temp_binary_data_21[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2012 D\xc3\xa9sir\xc3\xa9 Nuentsa-Wakam <desire.nuentsa_wakam@inria.fr>\r\n"
"// Copyright (C) 2012 Gael Guennebaud <gael.guennebaud@inria.fr>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPARSELU_MODULE_H\r\n"
"#define EIGEN_SPARSELU_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"/** \r\n"
"  * \\defgroup SparseLU_Module SparseLU module\r\n"
"  * This module defines a supernodal factorization of general sparse matrices.\r\n"
"  * The code is fully optimized for supernode-panel updates with specialized kernels.\r\n"
"  * Please, see the documentation of the SparseLU class for more details.\r\n"
"  */\r\n"
"\r\n"
"// Ordering interface\r\n"
"#include \"OrderingMethods\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"#include \"src/SparseLU/SparseLU_gemm_kernel.h\"\r\n"
"\r\n"
"#include \"src/SparseLU/SparseLU_Structs.h\"\r\n"
"#include \"src/SparseLU/SparseLU_SupernodalMatrix.h\"\r\n"
"#include \"src/SparseLU/SparseLUImpl.h\"\r\n"
"#include \"src/SparseCore/SparseColEtree.h\"\r\n"
"#include \"src/SparseLU/SparseLU_Memory.h\"\r\n"
"#include \"src/SparseLU/SparseLU_heap_relax_snode.h\"\r\n"
"#include \"src/SparseLU/SparseLU_relax_snode.h\"\r\n"
"#include \"src/SparseLU/SparseLU_pivotL.h\"\r\n"
"#include \"src/SparseLU/SparseLU_panel_dfs.h\"\r\n"
"#include \"src/SparseLU/SparseLU_kernel_bmod.h\"\r\n"
"#include \"src/SparseLU/SparseLU_panel_bmod.h\"\r\n"
"#include \"src/SparseLU/SparseLU_column_dfs.h\"\r\n"
"#include \"src/SparseLU/SparseLU_column_bmod.h\"\r\n"
"#include \"src/SparseLU/SparseLU_copy_to_ucol.h\"\r\n"
"#include \"src/SparseLU/SparseLU_pruneL.h\"\r\n"
"#include \"src/SparseLU/SparseLU_Utils.h\"\r\n"
"#include \"src/SparseLU/SparseLU.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_SPARSELU_MODULE_H\r\n";

const char* SparseLU = (const char*) temp_binary_data_21;

//================== SparseQR ==================
static const unsigned char temp_binary_data_22[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPARSEQR_MODULE_H\r\n"
"#define EIGEN_SPARSEQR_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"#include \"OrderingMethods\"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup SparseQR_Module SparseQR module\r\n"
"  * \\brief Provides QR decomposition for sparse matrices\r\n"
"  * \r\n"
"  * This module provides a simplicial version of the left-looking Sparse QR decomposition. \r\n"
"  * The columns of the input matrix should be reordered to limit the fill-in during the \r\n"
"  * decomposition. Built-in methods (COLAMD, AMD) or external  methods (METIS) can be used to this end.\r\n"
"  * See the \\link OrderingMethods_Module OrderingMethods\\endlink module for the list \r\n"
"  * of built-in and external ordering methods.\r\n"
"  * \r\n"
"  * \\code\r\n"
"  * #include <Eigen/SparseQR>\r\n"
"  * \\endcode\r\n"
"  * \r\n"
"  * \r\n"
"  */\r\n"
"\r\n"
"#include \"src/SparseCore/SparseColEtree.h\"\r\n"
"#include \"src/SparseQR/SparseQR.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif\r\n";

const char* SparseQR = (const char*) temp_binary_data_22;

//================== SPQRSupport ==================
static const unsigned char temp_binary_data_23[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SPQRSUPPORT_MODULE_H\r\n"
"#define EIGEN_SPQRSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"#include \"SuiteSparseQR.hpp\"\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup SPQRSupport_Module SuiteSparseQR module\r\n"
"  * \r\n"
"  * This module provides an interface to the SPQR library, which is part of the <a href=\"http://www.suitesparse.com\">suitesparse</a> package.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/SPQRSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the SPQR headers must be accessible from the include paths, and your binary must be linked to the SPQR library and its dependencies (Cholmod, AMD, COLAMD,...).\r\n"
"  * For a cmake based project, you can use our FindSPQR.cmake and FindCholmod.Cmake modules\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/CholmodSupport/CholmodSupport.h\"\r\n"
"#include \"src/SPQRSupport/SuiteSparseQRSupport.h\"\r\n"
"\r\n"
"#endif\r\n";

const char* SPQRSupport = (const char*) temp_binary_data_23;

//================== StdDeque ==================
static const unsigned char temp_binary_data_24[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2009 Gael Guennebaud <gael.guennebaud@inria.fr>\r\n"
"// Copyright (C) 2009 Hauke Heibel <hauke.heibel@googlemail.com>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_STDDEQUE_MODULE_H\r\n"
"#define EIGEN_STDDEQUE_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"#include <deque>\r\n"
"\r\n"
"#if EIGEN_COMP_MSVC && EIGEN_OS_WIN64 && (EIGEN_MAX_STATIC_ALIGN_BYTES<=16) /* MSVC auto aligns up to 16 bytes in 64 bit builds */\r\n"
"\r\n"
"#define EIGEN_DEFINE_STL_DEQUE_SPECIALIZATION(...)\r\n"
"\r\n"
"#else\r\n"
"\r\n"
"#include \"src/StlSupport/StdDeque.h\"\r\n"
"\r\n"
"#endif\r\n"
"\r\n"
"#endif // EIGEN_STDDEQUE_MODULE_H\r\n";

const char* StdDeque = (const char*) temp_binary_data_24;

//================== StdList ==================
static const unsigned char temp_binary_data_25[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2009 Hauke Heibel <hauke.heibel@googlemail.com>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_STDLIST_MODULE_H\r\n"
"#define EIGEN_STDLIST_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"#include <list>\r\n"
"\r\n"
"#if EIGEN_COMP_MSVC && EIGEN_OS_WIN64 && (EIGEN_MAX_STATIC_ALIGN_BYTES<=16) /* MSVC auto aligns up to 16 bytes in 64 bit builds */\r\n"
"\r\n"
"#define EIGEN_DEFINE_STL_LIST_SPECIALIZATION(...)\r\n"
"\r\n"
"#else\r\n"
"\r\n"
"#include \"src/StlSupport/StdList.h\"\r\n"
"\r\n"
"#endif\r\n"
"\r\n"
"#endif // EIGEN_STDLIST_MODULE_H\r\n";

const char* StdList = (const char*) temp_binary_data_25;

//================== StdVector ==================
static const unsigned char temp_binary_data_26[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// Copyright (C) 2009 Gael Guennebaud <gael.guennebaud@inria.fr>\r\n"
"// Copyright (C) 2009 Hauke Heibel <hauke.heibel@googlemail.com>\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_STDVECTOR_MODULE_H\r\n"
"#define EIGEN_STDVECTOR_MODULE_H\r\n"
"\r\n"
"#include \"Core\"\r\n"
"#include <vector>\r\n"
"\r\n"
"#if EIGEN_COMP_MSVC && EIGEN_OS_WIN64 && (EIGEN_MAX_STATIC_ALIGN_BYTES<=16) /* MSVC auto aligns up to 16 bytes in 64 bit builds */\r\n"
"\r\n"
"#define EIGEN_DEFINE_STL_VECTOR_SPECIALIZATION(...)\r\n"
"\r\n"
"#else\r\n"
"\r\n"
"#include \"src/StlSupport/StdVector.h\"\r\n"
"\r\n"
"#endif\r\n"
"\r\n"
"#endif // EIGEN_STDVECTOR_MODULE_H\r\n";

const char* StdVector = (const char*) temp_binary_data_26;

//================== SuperLUSupport ==================
static const unsigned char temp_binary_data_27[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SUPERLUSUPPORT_MODULE_H\r\n"
"#define EIGEN_SUPERLUSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"#ifdef EMPTY\r\n"
"#define EIGEN_EMPTY_WAS_ALREADY_DEFINED\r\n"
"#endif\r\n"
"\r\n"
"typedef int int_t;\r\n"
"#include <slu_Cnames.h>\r\n"
"#include <supermatrix.h>\r\n"
"#include <slu_util.h>\r\n"
"\r\n"
"// slu_util.h defines a preprocessor token named EMPTY which is really polluting,\r\n"
"// so we remove it in favor of a SUPERLU_EMPTY token.\r\n"
"// If EMPTY was already defined then we don't undef it.\r\n"
"\r\n"
"#if defined(EIGEN_EMPTY_WAS_ALREADY_DEFINED)\r\n"
"# undef EIGEN_EMPTY_WAS_ALREADY_DEFINED\r\n"
"#elif defined(EMPTY)\r\n"
"# undef EMPTY\r\n"
"#endif\r\n"
"\r\n"
"#define SUPERLU_EMPTY (-1)\r\n"
"\r\n"
"namespace Eigen { struct SluMatrix; }\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup SuperLUSupport_Module SuperLUSupport module\r\n"
"  *\r\n"
"  * This module provides an interface to the <a href=\"http://crd-legacy.lbl.gov/~xiaoye/SuperLU/\">SuperLU</a> library.\r\n"
"  * It provides the following factorization class:\r\n"
"  * - class SuperLU: a supernodal sequential LU factorization.\r\n"
"  * - class SuperILU: a supernodal sequential incomplete LU factorization (to be used as a preconditioner for iterative methods).\r\n"
"  *\r\n"
"  * \\warning This wrapper requires at least versions 4.0 of SuperLU. The 3.x versions are not supported.\r\n"
"  *\r\n"
"  * \\warning When including this module, you have to use SUPERLU_EMPTY instead of EMPTY which is no longer defined because it is too polluting.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/SuperLUSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the superlu headers must be accessible from the include paths, and your binary must be linked to the superlu library and its dependencies.\r\n"
"  * The dependencies depend on how superlu has been compiled.\r\n"
"  * For a cmake based project, you can use our FindSuperLU.cmake module to help you in this task.\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/SuperLUSupport/SuperLUSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_SUPERLUSUPPORT_MODULE_H\r\n";

const char* SuperLUSupport = (const char*) temp_binary_data_27;

//================== SVD ==================
static const unsigned char temp_binary_data_28[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_SVD_MODULE_H\r\n"
"#define EIGEN_SVD_MODULE_H\r\n"
"\r\n"
"#include \"QR\"\r\n"
"#include \"Householder\"\r\n"
"#include \"Jacobi\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"/** \\defgroup SVD_Module SVD module\r\n"
"  *\r\n"
"  *\r\n"
"  *\r\n"
"  * This module provides SVD decomposition for matrices (both real and complex).\r\n"
"  * Two decomposition algorithms are provided:\r\n"
"  *  - JacobiSVD implementing two-sided Jacobi iterations is numerically very accurate, fast for small matrices, but very slow for larger ones.\r\n"
"  *  - BDCSVD implementing a recursive divide & conquer strategy on top of an upper-bidiagonalization which remains fast for large problems.\r\n"
"  * These decompositions are accessible via the respective classes and following MatrixBase methods:\r\n"
"  *  - MatrixBase::jacobiSvd()\r\n"
"  *  - MatrixBase::bdcSvd()\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/SVD>\r\n"
"  * \\endcode\r\n"
"  */\r\n"
"\r\n"
"#include \"src/misc/RealSvd2x2.h\"\r\n"
"#include \"src/SVD/UpperBidiagonalization.h\"\r\n"
"#include \"src/SVD/SVDBase.h\"\r\n"
"#include \"src/SVD/JacobiSVD.h\"\r\n"
"#include \"src/SVD/BDCSVD.h\"\r\n"
"#if defined(EIGEN_USE_LAPACKE) && !defined(EIGEN_USE_LAPACKE_STRICT)\r\n"
"#ifdef EIGEN_USE_MKL\r\n"
"#include \"mkl_lapacke.h\"\r\n"
"#else\r\n"
"#include \"src/misc/lapacke.h\"\r\n"
"#endif\r\n"
"#include \"src/SVD/JacobiSVD_LAPACKE.h\"\r\n"
"#endif\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_SVD_MODULE_H\r\n";

const char* SVD = (const char*) temp_binary_data_28;

//================== UmfPackSupport ==================
static const unsigned char temp_binary_data_29[] =
"// This file is part of Eigen, a lightweight C++ template library\r\n"
"// for linear algebra.\r\n"
"//\r\n"
"// This Source Code Form is subject to the terms of the Mozilla\r\n"
"// Public License v. 2.0. If a copy of the MPL was not distributed\r\n"
"// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.\r\n"
"\r\n"
"#ifndef EIGEN_UMFPACKSUPPORT_MODULE_H\r\n"
"#define EIGEN_UMFPACKSUPPORT_MODULE_H\r\n"
"\r\n"
"#include \"SparseCore\"\r\n"
"\r\n"
"#include \"src/Core/util/DisableStupidWarnings.h\"\r\n"
"\r\n"
"extern \"C\" {\r\n"
"#include <umfpack.h>\r\n"
"}\r\n"
"\r\n"
"/** \\ingroup Support_modules\r\n"
"  * \\defgroup UmfPackSupport_Module UmfPackSupport module\r\n"
"  *\r\n"
"  * This module provides an interface to the UmfPack library which is part of the <a href=\"http://www.suitesparse.com\">suitesparse</a> package.\r\n"
"  * It provides the following factorization class:\r\n"
"  * - class UmfPackLU: a multifrontal sequential LU factorization.\r\n"
"  *\r\n"
"  * \\code\r\n"
"  * #include <Eigen/UmfPackSupport>\r\n"
"  * \\endcode\r\n"
"  *\r\n"
"  * In order to use this module, the umfpack headers must be accessible from the include paths, and your binary must be linked to the umfpack library and its dependencies.\r\n"
"  * The dependencies depend on how umfpack has been compiled.\r\n"
"  * For a cmake based project, you can use our FindUmfPack.cmake module to help you in this task.\r\n"
"  *\r\n"
"  */\r\n"
"\r\n"
"#include \"src/UmfPackSupport/UmfPackSupport.h\"\r\n"
"\r\n"
"#include \"src/Core/util/ReenableStupidWarnings.h\"\r\n"
"\r\n"
"#endif // EIGEN_UMFPACKSUPPORT_MODULE_H\r\n";

const char* UmfPackSupport = (const char*) temp_binary_data_29;

//================== default.nslayout ==================
static const unsigned char temp_binary_data_30[] =
"{\r\n"
"  \"mainLayout\": {\r\n"
"    \"type\": 1,\r\n"
"    \"width\": 1366,\r\n"
"    \"height\": 697,\r\n"
"    \"direction\": 2,\r\n"
"    \"shifters\": [\r\n"
"      {\r\n"
"        \"type\": 1,\r\n"
"        \"width\": 1366,\r\n"
"        \"height\": 697,\r\n"
"        \"direction\": 1,\r\n"
"        \"shifters\": [\r\n"
"          {\r\n"
"            \"type\": 1,\r\n"
"            \"width\": 394,\r\n"
"            \"height\": 697,\r\n"
"            \"direction\": 2,\r\n"
"            \"shifters\": [\r\n"
"              {\r\n"
"                \"type\": 0,\r\n"
"                \"width\": 394,\r\n"
"                \"height\": 346,\r\n"
"                \"currentContent\": \"Entities\",\r\n"
"                \"tabs\": [\r\n"
"                  {\r\n"
"                    \"name\": \"Entities\"\r\n"
"                  }\r\n"
"                ]\r\n"
"              },\r\n"
"              {\r\n"
"                \"type\": 0,\r\n"
"                \"width\": 394,\r\n"
"                \"height\": 345,\r\n"
"                \"currentContent\": \"Reactions\",\r\n"
"                \"tabs\": [\r\n"
"                  {\r\n"
"                    \"name\": \"Reactions\"\r\n"
"                  }\r\n"
"                ]\r\n"
"              }\r\n"
"            ]\r\n"
"          },\r\n"
"          {\r\n"
"            \"type\": 1,\r\n"
"            \"width\": 966,\r\n"
"            \"height\": 697,\r\n"
"            \"direction\": 1,\r\n"
"            \"shifters\": [\r\n"
"              {\r\n"
"                \"type\": 0,\r\n"
"                \"width\": 597,\r\n"
"                \"height\": 697,\r\n"
"                \"currentContent\": \"Simulation\",\r\n"
"                \"tabs\": [\r\n"
"                  {\r\n"
"                    \"name\": \"Simulation\"\r\n"
"                  }\r\n"
"                ]\r\n"
"              },\r\n"
"              {\r\n"
"                \"type\": 1,\r\n"
"                \"width\": 362,\r\n"
"                \"height\": 697,\r\n"
"                \"direction\": 2,\r\n"
"                \"shifters\": [\r\n"
"                  {\r\n"
"                    \"type\": 0,\r\n"
"                    \"width\": 362,\r\n"
"                    \"height\": 430,\r\n"
"                    \"currentContent\": \"Inspector\",\r\n"
"                    \"tabs\": [\r\n"
"                      {\r\n"
"                        \"name\": \"Inspector\"\r\n"
"                      }\r\n"
"                    ]\r\n"
"                  },\r\n"
"                  {\r\n"
"                    \"type\": 0,\r\n"
"                    \"width\": 362,\r\n"
"                    \"height\": 261,\r\n"
"                    \"currentContent\": \"Logger\",\r\n"
"                    \"tabs\": [\r\n"
"                      {\r\n"
"                        \"name\": \"Logger\"\r\n"
"                      },\r\n"
"                      {\r\n"
"                        \"name\": \"Warnings\"\r\n"
"                      }\r\n"
"                    ]\r\n"
"                  }\r\n"
"                ]\r\n"
"              }\r\n"
"            ]\r\n"
"          }\r\n"
"        ]\r\n"
"      }\r\n"
"    ]\r\n"
"  },\r\n"
"  \"windows\": null\r\n"
"}";

const char* default_nslayout = (const char*) temp_binary_data_30;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x71024ebe:  numBytes = 1206; return Cholesky;
        case 0xfe5a710f:  numBytes = 1948; return CholmodSupport;
        case 0x002023bf:  numBytes = 13183; return Core;
        case 0x03edd2ff:  numBytes = 129; return Dense;
        case 0x03fda00c:  numBytes = 37; return Eigen;
        case 0x80f6042e:  numBytes = 1837; return Eigenvalues;
        case 0x71e26c92:  numBytes = 1999; return Geometry;
        case 0xd03464ac:  numBytes = 858; return Householder;
        case 0xcb4ed54e:  numBytes = 2131; return IterativeLinearSolvers;
        case 0x83cc338a:  numBytes = 926; return Jacobi;
        case 0x0844161b:  numBytes = 1430; return KLUSupport;
        case 0x00000989:  numBytes = 1315; return LU;
        case 0x2ed44d09:  numBytes = 1026; return MetisSupport;
        case 0x20e2ff1e:  numBytes = 2521; return OrderingMethods;
        case 0x5790bfcd:  numBytes = 1151; return PardisoSupport;
        case 0xe4d2f3ae:  numBytes = 1800; return PaStiXSupport;
        case 0x00000a21:  numBytes = 1322; return QR;
        case 0xd49890e9:  numBytes = 939; return QtAlignedMalloc;
        case 0x93fa5640:  numBytes = 922; return Sparse;
        case 0x796264fe:  numBytes = 1272; return SparseCholesky;
        case 0xc68559ff:  numBytes = 2309; return SparseCore;
        case 0x7ebdcfc9:  numBytes = 1864; return SparseLU;
        case 0x7ebdd061:  numBytes = 1231; return SparseQR;
        case 0xc18be4b1:  numBytes = 1196; return SPQRSupport;
        case 0x54e6e25d:  numBytes = 824; return StdDeque;
        case 0xf23cb141:  numBytes = 752; return StdList;
        case 0x66a64526:  numBytes = 830; return StdVector;
        case 0x9831890b:  numBytes = 2307; return SuperLUSupport;
        case 0x00014241:  numBytes = 1634; return SVD;
        case 0x6ac119e8:  numBytes = 1422; return UmfPackSupport;
        case 0x1df0b56d:  numBytes = 2547; return default_nslayout;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "Cholesky",
    "CholmodSupport",
    "Core",
    "Dense",
    "Eigen",
    "Eigenvalues",
    "Geometry",
    "Householder",
    "IterativeLinearSolvers",
    "Jacobi",
    "KLUSupport",
    "LU",
    "MetisSupport",
    "OrderingMethods",
    "PardisoSupport",
    "PaStiXSupport",
    "QR",
    "QtAlignedMalloc",
    "Sparse",
    "SparseCholesky",
    "SparseCore",
    "SparseLU",
    "SparseQR",
    "SPQRSupport",
    "StdDeque",
    "StdList",
    "StdVector",
    "SuperLUSupport",
    "SVD",
    "UmfPackSupport",
    "default_nslayout"
};

const char* originalFilenames[] =
{
    "Cholesky",
    "CholmodSupport",
    "Core",
    "Dense",
    "Eigen",
    "Eigenvalues",
    "Geometry",
    "Householder",
    "IterativeLinearSolvers",
    "Jacobi",
    "KLUSupport",
    "LU",
    "MetisSupport",
    "OrderingMethods",
    "PardisoSupport",
    "PaStiXSupport",
    "QR",
    "QtAlignedMalloc",
    "Sparse",
    "SparseCholesky",
    "SparseCore",
    "SparseLU",
    "SparseQR",
    "SPQRSupport",
    "StdDeque",
    "StdList",
    "StdVector",
    "SuperLUSupport",
    "SVD",
    "UmfPackSupport",
    "default.nslayout"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
        if (strcmp (namedResourceList[i], resourceNameUTF8) == 0)
            return originalFilenames[i];

    return nullptr;
}

}
