name: Release Artifacts

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Windows
          path: ./artifacts

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Linux
          path: ./artifacts

      - name: Download macOS Intel Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Mac_intel
          path: ./artifacts

      - name: Download macOS Silicon Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Mac_silicon
          path: ./artifacts

      - name: Prepare Release Assets
        run: |
          mkdir -p release_assets
          mv ./Binaries/CI/App/*.exe release_assets/EmergeNS_Windows.exe
          mv ./Builds/LinuxMakefile_CI/*.AppImage release_assets/EmergeNS_Linux.AppImage
          mv ./Package/*.pkg release_assets/EmergeNS_Mac_Intel.pkg
          mv ./Package/*.pkg release_assets/EmergeNS_Mac_Silicon.pkg

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Windows.exe
          asset_name: EmergeNS_Windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Linux.AppImage
          asset_name: EmergeNS_Linux.AppImage
          asset_content_type: application/octet-stream

      - name: Upload macOS Intel Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Mac_Intel.pkg
          asset_name: EmergeNS_Mac_Intel.pkg
          asset_content_type: application/octet-stream

      - name: Upload macOS Silicon Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Mac_Silicon.pkg
          asset_name: EmergeNS_Mac_Silicon.pkg
          asset_content_type: application/octet-stream
