name: Release Artifacts

on:
  push:
    tags:
      - '*' # Matches any tag

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Windows
          path: ./artifacts/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Linux
          path: ./artifacts/linux

      - name: Download macOS Intel Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Mac_intel
          path: ./artifacts/macos-intel

      - name: Download macOS Silicon Artifact
        uses: actions/download-artifact@v4
        with:
          name: EmergeNS_Mac_silicon
          path: ./artifacts/macos-silicon

      - name: Prepare Release Assets
        run: |
          mkdir -p release_assets
          mv ./artifacts/windows/*.zip release_assets/EmergeNS_Windows.zip
          mv ./artifacts/linux/*.zip release_assets/EmergeNS_Linux.zip
          mv ./artifacts/macos-intel/*.zip release_assets/EmergeNS_Mac_Intel.zip
          mv ./artifacts/macos-silicon/*.zip release_assets/EmergeNS_Mac_Silicon.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Windows.zip
          asset_name: EmergeNS_Windows.zip
          asset_content_type: application/zip

      - name: Upload Linux Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Linux.zip
          asset_name: EmergeNS_Linux.zip
          asset_content_type: application/zip

      - name: Upload macOS Intel Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Mac_Intel.zip
          asset_name: EmergeNS_Mac_Intel.zip
          asset_content_type: application/zip

      - name: Upload macOS Silicon Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/EmergeNS_Mac_Silicon.zip
          asset_name: EmergeNS_Mac_Silicon.zip
          asset_content_type: application/zip
